# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PiholeMcp < Formula
  desc "Pi-hole v6 MCP server — DNS blocking, domain management, statistics and network administration"
  homepage "https://github.com/hexamatic/pihole-mcp"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/hexamatic/pihole-mcp/releases/download/v0.5.0/pihole-mcp_0.5.0_darwin_amd64.tar.gz"
      sha256 "c9c282da9035becc866bc6e9f8fc370154b470c880f64119b508746b3a4e7008"
    end
    on_arm do
      url "https://github.com/hexamatic/pihole-mcp/releases/download/v0.5.0/pihole-mcp_0.5.0_darwin_arm64.tar.gz"
      sha256 "0d87bc6333f17d486e8b644ea050702494032f1101cc9628248d8aaa02ab64b6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hexamatic/pihole-mcp/releases/download/v0.5.0/pihole-mcp_0.5.0_linux_amd64.tar.gz"
      sha256 "32810684e79465672d42e063390737f7dc53d5d7a2e942c63ba692de99f9753b"
    end
    on_arm do
      url "https://github.com/hexamatic/pihole-mcp/releases/download/v0.5.0/pihole-mcp_0.5.0_linux_arm64.tar.gz"
      sha256 "f82585d855a06ccc850515536c1fec64912b37f75cede5b04b7ade9256c9a050"
    end
  end

  def install
    bin.install "pihole-mcp"
  end

  test do
    assert_match "pihole-mcp", shell_output("#{bin}/pihole-mcp -version")
  end
end
