# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PiholeMcp < Formula
  desc "Pi-hole v6 MCP server — DNS blocking, domain management, statistics and network administration"
  homepage "https://github.com/hexamatic/pihole-mcp"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hexamatic/pihole-mcp/releases/download/v0.6.0/pihole-mcp_0.6.0_darwin_amd64.tar.gz"
      sha256 "1b3026a9cb6b84e87fae72114eaf5bd3c5b3ea54bb2a989e385a579107a93451"

      define_method(:install) do
        bin.install "pihole-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hexamatic/pihole-mcp/releases/download/v0.6.0/pihole-mcp_0.6.0_darwin_arm64.tar.gz"
      sha256 "9f5cae06e03245d477940275e6818ddae95ad95f5739f77738f77422e0c5b1c4"

      define_method(:install) do
        bin.install "pihole-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hexamatic/pihole-mcp/releases/download/v0.6.0/pihole-mcp_0.6.0_linux_amd64.tar.gz"
      sha256 "90e6024e9c769dbdc16b5463a428591ffb04ed9a1a534960d431cd7b7d03e89d"
      define_method(:install) do
        bin.install "pihole-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hexamatic/pihole-mcp/releases/download/v0.6.0/pihole-mcp_0.6.0_linux_arm64.tar.gz"
      sha256 "183fd2df01c42c3cb214c5aafeb0e95444f9adf11050d1421e772ad135a1bd59"
      define_method(:install) do
        bin.install "pihole-mcp"
      end
    end
  end

  test do
    assert_match "pihole-mcp", shell_output("#{bin}/pihole-mcp -version")
  end
end
