# This file was generated by GoReleaser. DO NOT EDIT.
cask "pihole-mcp" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "d1ddb0df6ad5674a584c659db1a62471fd826022c769e1e3b6548f89e074ded4"
      url "https://github.com/hexamatic/pihole-mcp/releases/download/v#{version}/pihole-mcp_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hexamatic/pihole-mcp"
    end
    on_arm do
      sha256 "31589360b05729ac2b9d4de34169df152e681c305dd56ed01efcddc6ceb65d50"
      url "https://github.com/hexamatic/pihole-mcp/releases/download/v#{version}/pihole-mcp_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hexamatic/pihole-mcp"
    end
  end

  on_linux do
    on_intel do
      sha256 "ceee1b6ee8d7fb0928502fed82e566fb5497ac8e52785b5b63532edc97cd3b82"
      url "https://github.com/hexamatic/pihole-mcp/releases/download/v#{version}/pihole-mcp_#{version}_linux_amd64.tar.gz",
        verified: "github.com/hexamatic/pihole-mcp"
    end
    on_arm do
      sha256 "3801cd14a3e8cfc866b1d6d6235d8e4adc5adc24591243e5fcb84607bef6d039"
      url "https://github.com/hexamatic/pihole-mcp/releases/download/v#{version}/pihole-mcp_#{version}_linux_arm64.tar.gz",
        verified: "github.com/hexamatic/pihole-mcp"
    end
  end

  name "pihole-mcp"
  desc "Pi-hole v6 MCP server — DNS blocking, domain management, statistics and network administration"
  homepage "https://github.com/hexamatic/pihole-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pihole-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pihole-mcp"]
    end
  end

  # No zap stanza required

end
